# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b930827e3f06e8b7068a346ddb542daf94be60c731ce8884f55827e7474333e5dc186e4eca36ab02b4e4cae98e2e47cae51c946c05551e4b5da76b68f4e05b7

test:
  secret_key_base: a34ebe02bd81544cbded45bb00922c438582cf9fe8fae13d2e4e9f36267250b3e077c3da59ec0ed8b1cdccc6ccd35404af7efbf7cbccd13e0bc8b2837233e15f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
