# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

##Municipios y departamentos de colombia

# Department.create( name: "")
# Department.create( name: "BOGOTA")
# Department.create( name: "ANTIOQUIA")
# Department.create( name: "ATLANTICO")
# Department.create( name: "BOLIVAR")
# Department.create( name: "BOYACA")
# Department.create( name: "CALDAS")
# Department.create( name: "CAQUETA")
# Department.create( name: "CAUCA")
# Department.create( name: "CESAR")
# Department.create( name: "CORDOBA")
# Department.create( name: "CUNDINAMARCA")
# Department.create( name: "CHOCO")
# Department.create( name: "HUILA")
# Department.create( name: "LA GUAJIRA")
# Department.create( name: "MAGDALENA")
# Department.create( name: "META")
# Department.create( name: "NARIÑO")
# Department.create( name: "N. DE SANTANDER")
# Department.create( name: "QUINDIO")
# Department.create( name: "RISARALDA")
# Department.create( name: "SANTANDER")
# Department.create( name: "SUCRE")
# Department.create( name: "TOLIMA")
# Department.create( name: "VALLE DEL CAUCA")
# Department.create( name: "ARAUCA")
# Department.create( name: "CASANARE")
# Department.create( name: "PUTUMAYO")
# Department.create( name: "SAN ANDRES")
# Department.create( name: "AMAZONAS")
# Department.create( name: "GUAINIA")
# Department.create( name: "GUAVIARE")
# Department.create( name: "VAUPES")
# Department.create( name: "VICHADA")

# Minicipality.create(name:  "")
# Minicipality.create(name:  "BOGOTA, D.C.")
# Minicipality.create(name:  "ABEJORRAL")
# Minicipality.create(name:  "ABREGO")
# Minicipality.create(name:  "ABRIAQUI")
# Minicipality.create(name:  "ACACIAS")
# Minicipality.create(name:  "ACANDI")
# Minicipality.create(name:  "ACEVEDO")
# Minicipality.create(name:  "ACHI")
# Minicipality.create(name:  "AGRADO")
# Minicipality.create(name:  "AGUA DE DIOS")
# Minicipality.create(name:  "AGUACHICA")
# Minicipality.create(name:  "AGUADA")
# Minicipality.create(name:  "AGUADAS")
# Minicipality.create(name:  "AGUAZUL")
# Minicipality.create(name:  "AGUSTIN CODAZZI")
# Minicipality.create(name:  "AIPE")
# Minicipality.create(name:  "ALBAN")
# Minicipality.create(name:  "ALBAN")
# Minicipality.create(name:  "ALBANIA")
# Minicipality.create(name:  "ALBANIA")
# Minicipality.create(name:  "ALBANIA")
# Minicipality.create(name:  "ALCALA")
# Minicipality.create(name:  "ALDANA")
# Minicipality.create(name:  "ALEJANDRIA")
# Minicipality.create(name:  "ALGARROBO")
# Minicipality.create(name:  "ALGECIRAS")
# Minicipality.create(name:  "ALMAGUER")
# Minicipality.create(name:  "ALMEIDA")
# Minicipality.create(name:  "ALPUJARRA")
# Minicipality.create(name:  "ALTAMIRA")
# Minicipality.create(name:  "ALTO BAUDO")
# Minicipality.create(name:  "ALTOS DEL ROSARIO")
# Minicipality.create(name:  "ALVARADO")
# Minicipality.create(name:  "AMAGA")
# Minicipality.create(name:  "AMALFI")
# Minicipality.create(name:  "AMBALEMA")
# Minicipality.create(name:  "ANAPOIMA")
# Minicipality.create(name:  "ANCUYA")
# Minicipality.create(name:  "ANDALUCIA")
# Minicipality.create(name:  "ANDES")
# Minicipality.create(name:  "ANGELOPOLIS")
# Minicipality.create(name:  "ANGOSTURA")
# Minicipality.create(name:  "ANOLAIMA")
# Minicipality.create(name:  "ANORI")
# Minicipality.create(name:  "ANSERMA")
# Minicipality.create(name:  "ANSERMANUEVO")
# Minicipality.create(name:  "ANZA")
# Minicipality.create(name:  "ANZOATEGUI")
# Minicipality.create(name:  "APARTADO")
# Minicipality.create(name:  "APIA")
# Minicipality.create(name:  "APULO")
# Minicipality.create(name:  "AQUITANIA")
# Minicipality.create(name:  "ARACATACA")
# Minicipality.create(name:  "ARANZAZU")
# Minicipality.create(name:  "ARATOCA")
# Minicipality.create(name:  "ARAUCA")
# Minicipality.create(name:  "ARAUQUITA")
# Minicipality.create(name:  "ARBELAEZ")
# Minicipality.create(name:  "ARBOLEDA")
# Minicipality.create(name:  "ARBOLEDAS")
# Minicipality.create(name:  "ARBOLETES")
# Minicipality.create(name:  "ARCABUCO")
# Minicipality.create(name:  "ARENAL")
# Minicipality.create(name:  "ARGELIA")
# Minicipality.create(name:  "ARGELIA")
# Minicipality.create(name:  "ARGELIA")
# Minicipality.create(name:  "ARIGUANI")
# Minicipality.create(name:  "ARJONA")
# Minicipality.create(name:  "ARMENIA")
# Minicipality.create(name:  "ARMENIA")
# Minicipality.create(name:  "ARMERO")
# Minicipality.create(name:  "ARROYOHONDO")
# Minicipality.create(name:  "ASTREA")
# Minicipality.create(name:  "ATACO")
# Minicipality.create(name:  "ATRATO")
# Minicipality.create(name:  "AYAPEL")
# Minicipality.create(name:  "BAGADO")
# Minicipality.create(name:  "BAHIA SOLANO")
# Minicipality.create(name:  "BAJO BAUDO")
# Minicipality.create(name:  "BALBOA")
# Minicipality.create(name:  "BALBOA")
# Minicipality.create(name:  "BARANOA")
# Minicipality.create(name:  "BARAYA")
# Minicipality.create(name:  "BARBACOAS")
# Minicipality.create(name:  "BARBOSA")
# Minicipality.create(name:  "BARBOSA")
# Minicipality.create(name:  "BARICHARA")
# Minicipality.create(name:  "BARRANCA DE UPIA")
# Minicipality.create(name:  "BARRANCABERMEJA")
# Minicipality.create(name:  "BARRANCAS")
# Minicipality.create(name:  "BARRANCO DE LOBA")
# Minicipality.create(name:  "BARRANCO MINAS")
# Minicipality.create(name:  "BARRANQUILLA")
# Minicipality.create(name:  "BECERRIL")
# Minicipality.create(name:  "BELALCAZAR")
# Minicipality.create(name:  "BELEN")
# Minicipality.create(name:  "BELEN")
# Minicipality.create(name:  "BELEN DE LOS ANDAQUIES")
# Minicipality.create(name:  "BELEN DE UMBRIA")
# Minicipality.create(name:  "BELLO")
# Minicipality.create(name:  "BELMIRA")
# Minicipality.create(name:  "BELTRAN")
# Minicipality.create(name:  "BERBEO")
# Minicipality.create(name:  "BETANIA")
# Minicipality.create(name:  "BETEITIVA")
# Minicipality.create(name:  "BETULIA")
# Minicipality.create(name:  "BETULIA")
# Minicipality.create(name:  "BITUIMA")
# Minicipality.create(name:  "BOAVITA")
# Minicipality.create(name:  "BOCHALEMA")
# Minicipality.create(name:  "BOJACA")
# Minicipality.create(name:  "BOJAYA")
# Minicipality.create(name:  "BOLIVAR")
# Minicipality.create(name:  "BOLIVAR")
# Minicipality.create(name:  "BOLIVAR")
# Minicipality.create(name:  "BOSCONIA")
# Minicipality.create(name:  "BOYACA")
# Minicipality.create(name:  "BRICEÑO")
# Minicipality.create(name:  "BRICEÑO")
# Minicipality.create(name:  "BUCARAMANGA")
# Minicipality.create(name:  "BUCARASICA")
# Minicipality.create(name:  "BUENAVENTURA")
# Minicipality.create(name:  "BUENAVISTA")
# Minicipality.create(name:  "BUENAVISTA")
# Minicipality.create(name:  "BUENAVISTA")
# Minicipality.create(name:  "BUENAVISTA")
# Minicipality.create(name:  "BUENOS AIRES")
# Minicipality.create(name:  "BUESACO")
# Minicipality.create(name:  "BUGALAGRANDE")
# Minicipality.create(name:  "BURITICA")
# Minicipality.create(name:  "BUSBANZA")
# Minicipality.create(name:  "CABRERA")
# Minicipality.create(name:  "CABRERA")
# Minicipality.create(name:  "CABUYARO")
# Minicipality.create(name:  "CACAHUAL")
# Minicipality.create(name:  "CACERES")
# Minicipality.create(name:  "CACHIPAY")
# Minicipality.create(name:  "CACHIRA")
# Minicipality.create(name:  "CACOTA")
# Minicipality.create(name:  "CAICEDO")
# Minicipality.create(name:  "CAICEDONIA")
# Minicipality.create(name:  "CAIMITO")
# Minicipality.create(name:  "CAJAMARCA")
# Minicipality.create(name:  "CAJIBIO")
# Minicipality.create(name:  "CAJICA")
# Minicipality.create(name:  "CALAMAR")
# Minicipality.create(name:  "CALAMAR")
# Minicipality.create(name:  "CALARCA")
# Minicipality.create(name:  "CALDAS")
# Minicipality.create(name:  "CALDAS")
# Minicipality.create(name:  "CALDONO")
# Minicipality.create(name:  "CALI")
# Minicipality.create(name:  "CALIFORNIA")
# Minicipality.create(name:  "CALIMA")
# Minicipality.create(name:  "CALOTO")
# Minicipality.create(name:  "CAMPAMENTO")
# Minicipality.create(name:  "CAMPO DE LA CRUZ")
# Minicipality.create(name:  "CAMPOALEGRE")
# Minicipality.create(name:  "CAMPOHERMOSO")
# Minicipality.create(name:  "CANALETE")
# Minicipality.create(name:  "CANDELARIA")
# Minicipality.create(name:  "CANDELARIA")
# Minicipality.create(name:  "CANTAGALLO")
# Minicipality.create(name:  "CAÑASGORDAS")
# Minicipality.create(name:  "CAPARRAPI")
# Minicipality.create(name:  "CAPITANEJO")
# Minicipality.create(name:  "CAQUEZA")
# Minicipality.create(name:  "CARACOLI")
# Minicipality.create(name:  "CARAMANTA")
# Minicipality.create(name:  "CARCASI")
# Minicipality.create(name:  "CAREPA")
# Minicipality.create(name:  "CARMEN DE APICALA")
# Minicipality.create(name:  "CARMEN DE CARUPA")
# Minicipality.create(name:  "CARMEN DEL DARIEN")
# Minicipality.create(name:  "CAROLINA")
# Minicipality.create(name:  "CARTAGENA")
# Minicipality.create(name:  "CARTAGENA DEL CHAIRA")
# Minicipality.create(name:  "CARTAGO")
# Minicipality.create(name:  "CARURU")
# Minicipality.create(name:  "CASABIANCA")
# Minicipality.create(name:  "CASTILLA LA NUEVA")
# Minicipality.create(name:  "CAUCASIA")
# Minicipality.create(name:  "CEPITA")
# Minicipality.create(name:  "CERETE")
# Minicipality.create(name:  "CERINZA")
# Minicipality.create(name:  "CERRITO")
# Minicipality.create(name:  "CERRO SAN ANTONIO")
# Minicipality.create(name:  "CERTEGUI")
# Minicipality.create(name:  "CHACHAGsI")
# Minicipality.create(name:  "CHAGUANI")
# Minicipality.create(name:  "CHALAN")
# Minicipality.create(name:  "CHAMEZA")
# Minicipality.create(name:  "CHAPARRAL")
# Minicipality.create(name:  "CHARALA")
# Minicipality.create(name:  "CHARTA")
# Minicipality.create(name:  "CHIA")
# Minicipality.create(name:  "CHIBOLO")
# Minicipality.create(name:  "CHIGORODO")
# Minicipality.create(name:  "CHIMA")
# Minicipality.create(name:  "CHIMA")
# Minicipality.create(name:  "CHIMICHAGUA")
# Minicipality.create(name:  "CHINACOTA")
# Minicipality.create(name:  "CHINAVITA")
# Minicipality.create(name:  "CHINCHINA")
# Minicipality.create(name:  "CHINU")
# Minicipality.create(name:  "CHIPAQUE")
# Minicipality.create(name:  "CHIPATA")
# Minicipality.create(name:  "CHIQUINQUIRA")
# Minicipality.create(name:  "CHIQUIZA")
# Minicipality.create(name:  "CHIRIGUANA")
# Minicipality.create(name:  "CHISCAS")
# Minicipality.create(name:  "CHITA")
# Minicipality.create(name:  "CHITAGA")
# Minicipality.create(name:  "CHITARAQUE")
# Minicipality.create(name:  "CHIVATA")
# Minicipality.create(name:  "CHIVOR")
# Minicipality.create(name:  "CHOACHI")
# Minicipality.create(name:  "CHOCONTA")
# Minicipality.create(name:  "CICUCO")
# Minicipality.create(name:  "CIENAGA")
# Minicipality.create(name:  "CIENAGA DE ORO")
# Minicipality.create(name:  "CIENEGA")
# Minicipality.create(name:  "CIMITARRA")
# Minicipality.create(name:  "CIRCASIA")
# Minicipality.create(name:  "CISNEROS")
# Minicipality.create(name:  "CIUDAD BOLIVAR")
# Minicipality.create(name:  "CLEMENCIA")
# Minicipality.create(name:  "COCORNA")
# Minicipality.create(name:  "COELLO")
# Minicipality.create(name:  "COGUA")
# Minicipality.create(name:  "COLOMBIA")
# Minicipality.create(name:  "COLON")
# Minicipality.create(name:  "COLON")
# Minicipality.create(name:  "COLOSO")
# Minicipality.create(name:  "COMBITA")
# Minicipality.create(name:  "CONCEPCION")
# Minicipality.create(name:  "CONCEPCION")
# Minicipality.create(name:  "CONCORDIA")
# Minicipality.create(name:  "CONCORDIA")
# Minicipality.create(name:  "CONDOTO")
# Minicipality.create(name:  "CONFINES")
# Minicipality.create(name:  "CONSACA")
# Minicipality.create(name:  "CONTADERO")
# Minicipality.create(name:  "CONTRATACION")
# Minicipality.create(name:  "CONVENCION")
# Minicipality.create(name:  "COPACABANA")
# Minicipality.create(name:  "COPER")
# Minicipality.create(name:  "CORDOBA")
# Minicipality.create(name:  "CORDOBA")
# Minicipality.create(name:  "CORDOBA")
# Minicipality.create(name:  "CORINTO")
# Minicipality.create(name:  "COROMORO")
# Minicipality.create(name:  "COROZAL")
# Minicipality.create(name:  "CORRALES")
# Minicipality.create(name:  "COTA")
# Minicipality.create(name:  "COTORRA")
# Minicipality.create(name:  "COVARACHIA")
# Minicipality.create(name:  "COVEÑAS")
# Minicipality.create(name:  "COYAIMA")
# Minicipality.create(name:  "CRAVO NORTE")
# Minicipality.create(name:  "CUASPUD")
# Minicipality.create(name:  "CUBARA")
# Minicipality.create(name:  "CUBARRAL")
# Minicipality.create(name:  "CUCAITA")
# Minicipality.create(name:  "CUCUNUBA")
# Minicipality.create(name:  "CUCUTA")
# Minicipality.create(name:  "CUCUTILLA")
# Minicipality.create(name:  "CUITIVA")
# Minicipality.create(name:  "CUMARAL")
# Minicipality.create(name:  "CUMARIBO")
# Minicipality.create(name:  "CUMBAL")
# Minicipality.create(name:  "CUMBITARA")
# Minicipality.create(name:  "CUNDAY")
# Minicipality.create(name:  "CURILLO")
# Minicipality.create(name:  "CURITI")
# Minicipality.create(name:  "CURUMANI")
# Minicipality.create(name:  "DABEIBA")
# Minicipality.create(name:  "DAGUA")
# Minicipality.create(name:  "DIBULLA")
# Minicipality.create(name:  "DISTRACCION")
# Minicipality.create(name:  "DOLORES")
# Minicipality.create(name:  "DON MATIAS")
# Minicipality.create(name:  "DOSQUEBRADAS")
# Minicipality.create(name:  "DUITAMA")
# Minicipality.create(name:  "DURANIA")
# Minicipality.create(name:  "EBEJICO")
# Minicipality.create(name:  "EL AGUILA")
# Minicipality.create(name:  "EL BAGRE")
# Minicipality.create(name:  "EL BANCO")
# Minicipality.create(name:  "EL CAIRO")
# Minicipality.create(name:  "EL CALVARIO")
# Minicipality.create(name:  "EL CANTON DEL SAN PABLO")
# Minicipality.create(name:  "EL CARMEN")
# Minicipality.create(name:  "EL CARMEN DE ATRATO")
# Minicipality.create(name:  "EL CARMEN DE BOLIVAR")
# Minicipality.create(name:  "EL CARMEN DE CHUCURI")
# Minicipality.create(name:  "EL CARMEN DE VIBORAL")
# Minicipality.create(name:  "EL CASTILLO")
# Minicipality.create(name:  "EL CERRITO")
# Minicipality.create(name:  "EL CHARCO")
# Minicipality.create(name:  "EL COCUY")
# Minicipality.create(name:  "EL COLEGIO")
# Minicipality.create(name:  "EL COPEY")
# Minicipality.create(name:  "EL DONCELLO")
# Minicipality.create(name:  "EL DORADO")
# Minicipality.create(name:  "EL DOVIO")
# Minicipality.create(name:  "EL ENCANTO")
# Minicipality.create(name:  "EL ESPINO")
# Minicipality.create(name:  "EL GUACAMAYO")
# Minicipality.create(name:  "EL GUAMO")
# Minicipality.create(name:  "EL LITORAL DEL SAN JUAN")
# Minicipality.create(name:  "EL MOLINO")
# Minicipality.create(name:  "EL PASO")
# Minicipality.create(name:  "EL PAUJIL")
# Minicipality.create(name:  "EL PEÑOL")
# Minicipality.create(name:  "EL PEÑON")
# Minicipality.create(name:  "EL PEÑON")
# Minicipality.create(name:  "EL PEÑON")
# Minicipality.create(name:  "EL PIÑON")
# Minicipality.create(name:  "EL PLAYON")
# Minicipality.create(name:  "EL RETEN")
# Minicipality.create(name:  "EL RETORNO")
# Minicipality.create(name:  "EL ROBLE")
# Minicipality.create(name:  "EL ROSAL")
# Minicipality.create(name:  "EL ROSARIO")
# Minicipality.create(name:  "EL SANTUARIO")
# Minicipality.create(name:  "EL TABLON DE GOMEZ")
# Minicipality.create(name:  "EL TAMBO")
# Minicipality.create(name:  "EL TAMBO")
# Minicipality.create(name:  "EL TARRA")
# Minicipality.create(name:  "EL ZULIA")
# Minicipality.create(name:  "ELIAS")
# Minicipality.create(name:  "ENCINO")
# Minicipality.create(name:  "ENCISO")
# Minicipality.create(name:  "ENTRERRIOS")
# Minicipality.create(name:  "ENVIGADO")
# Minicipality.create(name:  "ESPINAL")
# Minicipality.create(name:  "FACATATIVA")
# Minicipality.create(name:  "FALAN")
# Minicipality.create(name:  "FILADELFIA")
# Minicipality.create(name:  "FILANDIA")
# Minicipality.create(name:  "FIRAVITOBA")
# Minicipality.create(name:  "FLANDES")
# Minicipality.create(name:  "FLORENCIA")
# Minicipality.create(name:  "FLORENCIA")
# Minicipality.create(name:  "FLORESTA")
# Minicipality.create(name:  "FLORIAN")
# Minicipality.create(name:  "FLORIDA")
# Minicipality.create(name:  "FLORIDABLANCA")
# Minicipality.create(name:  "FOMEQUE")
# Minicipality.create(name:  "FONSECA")
# Minicipality.create(name:  "FORTUL")
# Minicipality.create(name:  "FOSCA")
# Minicipality.create(name:  "FRANCISCO PIZARRO")
# Minicipality.create(name:  "FREDONIA")
# Minicipality.create(name:  "FRESNO")
# Minicipality.create(name:  "FRONTINO")
# Minicipality.create(name:  "FUENTE DE ORO")
# Minicipality.create(name:  "FUNDACION")
# Minicipality.create(name:  "FUNES")
# Minicipality.create(name:  "FUNZA")
# Minicipality.create(name:  "FUQUENE")
# Minicipality.create(name:  "FUSAGASUGA")
# Minicipality.create(name:  "GACHALA")
# Minicipality.create(name:  "GACHANCIPA")
# Minicipality.create(name:  "GACHANTIVA")
# Minicipality.create(name:  "GACHETA")
# Minicipality.create(name:  "GALAN")
# Minicipality.create(name:  "GALAPA")
# Minicipality.create(name:  "GALERAS")
# Minicipality.create(name:  "GAMA")
# Minicipality.create(name:  "GAMARRA")
# Minicipality.create(name:  "GAMBITA")
# Minicipality.create(name:  "GAMEZA")
# Minicipality.create(name:  "GARAGOA")
# Minicipality.create(name:  "GARZON")
# Minicipality.create(name:  "GENOVA")
# Minicipality.create(name:  "GIGANTE")
# Minicipality.create(name:  "GINEBRA")
# Minicipality.create(name:  "GIRALDO")
# Minicipality.create(name:  "GIRARDOT")
# Minicipality.create(name:  "GIRARDOTA")
# Minicipality.create(name:  "GIRON")
# Minicipality.create(name:  "GOMEZ PLATA")
# Minicipality.create(name:  "GONZALEZ")
# Minicipality.create(name:  "GRAMALOTE")
# Minicipality.create(name:  "GRANADA")
# Minicipality.create(name:  "GRANADA")
# Minicipality.create(name:  "GRANADA")
# Minicipality.create(name:  "GsEPSA")
# Minicipality.create(name:  "GsICAN")
# Minicipality.create(name:  "GUACA")
# Minicipality.create(name:  "GUACAMAYAS")
# Minicipality.create(name:  "GUACARI")
# Minicipality.create(name:  "GUACHENE")
# Minicipality.create(name:  "GUACHETA")
# Minicipality.create(name:  "GUACHUCAL")
# Minicipality.create(name:  "GUADALAJARA DE BUGA")
# Minicipality.create(name:  "GUADALUPE")
# Minicipality.create(name:  "GUADALUPE")
# Minicipality.create(name:  "GUADALUPE")
# Minicipality.create(name:  "GUADUAS")
# Minicipality.create(name:  "GUAITARILLA")
# Minicipality.create(name:  "GUALMATAN")
# Minicipality.create(name:  "GUAMAL")
# Minicipality.create(name:  "GUAMAL")
# Minicipality.create(name:  "GUAMO")
# Minicipality.create(name:  "GUAPI")
# Minicipality.create(name:  "GUAPOTA")
# Minicipality.create(name:  "GUARANDA")
# Minicipality.create(name:  "GUARNE")
# Minicipality.create(name:  "GUASCA")
# Minicipality.create(name:  "GUATAPE")
# Minicipality.create(name:  "GUATAQUI")
# Minicipality.create(name:  "GUATAVITA")
# Minicipality.create(name:  "GUATEQUE")
# Minicipality.create(name:  "GUATICA")
# Minicipality.create(name:  "GUAVATA")
# Minicipality.create(name:  "GUAYABAL DE SIQUIMA")
# Minicipality.create(name:  "GUAYABETAL")
# Minicipality.create(name:  "GUAYATA")
# Minicipality.create(name:  "GUTIERREZ")
# Minicipality.create(name:  "HACARI")
# Minicipality.create(name:  "HATILLO DE LOBA")
# Minicipality.create(name:  "HATO")
# Minicipality.create(name:  "HATO COROZAL")
# Minicipality.create(name:  "HATONUEVO")
# Minicipality.create(name:  "HELICONIA")
# Minicipality.create(name:  "HERRAN")
# Minicipality.create(name:  "HERVEO")
# Minicipality.create(name:  "HISPANIA")
# Minicipality.create(name:  "HOBO")
# Minicipality.create(name:  "HONDA")
# Minicipality.create(name:  "IBAGUE")
# Minicipality.create(name:  "ICONONZO")
# Minicipality.create(name:  "ILES")
# Minicipality.create(name:  "IMUES")
# Minicipality.create(name:  "INIRIDA")
# Minicipality.create(name:  "INZA")
# Minicipality.create(name:  "IPIALES")
# Minicipality.create(name:  "IQUIRA")
# Minicipality.create(name:  "ISNOS")
# Minicipality.create(name:  "ISTMINA")
# Minicipality.create(name:  "ITAGUI")
# Minicipality.create(name:  "ITUANGO")
# Minicipality.create(name:  "IZA")
# Minicipality.create(name:  "JAMBALO")
# Minicipality.create(name:  "JAMUNDI")
# Minicipality.create(name:  "JARDIN")
# Minicipality.create(name:  "JENESANO")
# Minicipality.create(name:  "JERICO")
# Minicipality.create(name:  "JERICO")
# Minicipality.create(name:  "JERUSALEN")
# Minicipality.create(name:  "JESUS MARIA")
# Minicipality.create(name:  "JORDAN")
# Minicipality.create(name:  "JUAN DE ACOSTA")
# Minicipality.create(name:  "JUNIN")
# Minicipality.create(name:  "JURADO")
# Minicipality.create(name:  "LA APARTADA")
# Minicipality.create(name:  "LA ARGENTINA")
# Minicipality.create(name:  "LA BELLEZA")
# Minicipality.create(name:  "LA CALERA")
# Minicipality.create(name:  "LA CAPILLA")
# Minicipality.create(name:  "LA CEJA")
# Minicipality.create(name:  "LA CELIA")
# Minicipality.create(name:  "LA CHORRERA")
# Minicipality.create(name:  "LA CRUZ")
# Minicipality.create(name:  "LA CUMBRE")
# Minicipality.create(name:  "LA DORADA")
# Minicipality.create(name:  "LA ESPERANZA")
# Minicipality.create(name:  "LA ESTRELLA")
# Minicipality.create(name:  "LA FLORIDA")
# Minicipality.create(name:  "LA GLORIA")
# Minicipality.create(name:  "LA GUADALUPE")
# Minicipality.create(name:  "LA JAGUA DE IBIRICO")
# Minicipality.create(name:  "LA JAGUA DEL PILAR")
# Minicipality.create(name:  "LA LLANADA")
# Minicipality.create(name:  "LA MACARENA")
# Minicipality.create(name:  "LA MERCED")
# Minicipality.create(name:  "LA MESA")
# Minicipality.create(name:  "LA MONTAÑITA")
# Minicipality.create(name:  "LA PALMA")
# Minicipality.create(name:  "LA PAZ")
# Minicipality.create(name:  "LA PAZ")
# Minicipality.create(name:  "LA PEDRERA")
# Minicipality.create(name:  "LA PEÑA")
# Minicipality.create(name:  "LA PINTADA")
# Minicipality.create(name:  "LA PLATA")
# Minicipality.create(name:  "LA PLAYA")
# Minicipality.create(name:  "LA PRIMAVERA")
# Minicipality.create(name:  "LA SALINA")
# Minicipality.create(name:  "LA SIERRA")
# Minicipality.create(name:  "LA TEBAIDA")
# Minicipality.create(name:  "LA TOLA")
# Minicipality.create(name:  "LA UNION")
# Minicipality.create(name:  "LA UNION")
# Minicipality.create(name:  "LA UNION")
# Minicipality.create(name:  "LA UNION")
# Minicipality.create(name:  "LA UVITA")
# Minicipality.create(name:  "LA VEGA")
# Minicipality.create(name:  "LA VEGA")
# Minicipality.create(name:  "LA VICTORIA")
# Minicipality.create(name:  "LA VICTORIA")
# Minicipality.create(name:  "LA VICTORIA")
# Minicipality.create(name:  "LA VIRGINIA")
# Minicipality.create(name:  "LABATECA")
# Minicipality.create(name:  "LABRANZAGRANDE")
# Minicipality.create(name:  "LANDAZURI")
# Minicipality.create(name:  "LEBRIJA")
# Minicipality.create(name:  "LEGUIZAMO")
# Minicipality.create(name:  "LEIVA")
# Minicipality.create(name:  "LEJANIAS")
# Minicipality.create(name:  "LENGUAZAQUE")
# Minicipality.create(name:  "LERIDA")
# Minicipality.create(name:  "LETICIA")
# Minicipality.create(name:  "LIBANO")
# Minicipality.create(name:  "LIBORINA")
# Minicipality.create(name:  "LINARES")
# Minicipality.create(name:  "LLORO")
# Minicipality.create(name:  "LOPEZ")
# Minicipality.create(name:  "LORICA")
# Minicipality.create(name:  "LOS ANDES")
# Minicipality.create(name:  "LOS CORDOBAS")
# Minicipality.create(name:  "LOS PALMITOS")
# Minicipality.create(name:  "LOS PATIOS")
# Minicipality.create(name:  "LOS SANTOS")
# Minicipality.create(name:  "LOURDES")
# Minicipality.create(name:  "LURUACO")
# Minicipality.create(name:  "MACANAL")
# Minicipality.create(name:  "MACARAVITA")
# Minicipality.create(name:  "MACEO")
# Minicipality.create(name:  "MACHETA")
# Minicipality.create(name:  "MADRID")
# Minicipality.create(name:  "MAGANGUE")
# Minicipality.create(name:  "MAGsI")
# Minicipality.create(name:  "MAHATES")
# Minicipality.create(name:  "MAICAO")
# Minicipality.create(name:  "MAJAGUAL")
# Minicipality.create(name:  "MALAGA")
# Minicipality.create(name:  "MALAMBO")
# Minicipality.create(name:  "MALLAMA")
# Minicipality.create(name:  "MANATI")
# Minicipality.create(name:  "MANAURE")
# Minicipality.create(name:  "MANAURE")
# Minicipality.create(name:  "MANI")
# Minicipality.create(name:  "MANIZALES")
# Minicipality.create(name:  "MANTA")
# Minicipality.create(name:  "MANZANARES")
# Minicipality.create(name:  "MAPIRIPAN")
# Minicipality.create(name:  "MAPIRIPANA")
# Minicipality.create(name:  "MARGARITA")
# Minicipality.create(name:  "MARIA LA BAJA")
# Minicipality.create(name:  "MARINILLA")
# Minicipality.create(name:  "MARIPI")
# Minicipality.create(name:  "MARIQUITA")
# Minicipality.create(name:  "MARMATO")
# Minicipality.create(name:  "MARQUETALIA")
# Minicipality.create(name:  "MARSELLA")
# Minicipality.create(name:  "MARULANDA")
# Minicipality.create(name:  "MATANZA")
# Minicipality.create(name:  "MEDELLIN")
# Minicipality.create(name:  "MEDINA")
# Minicipality.create(name:  "MEDIO ATRATO")
# Minicipality.create(name:  "MEDIO BAUDO")
# Minicipality.create(name:  "MEDIO SAN JUAN")
# Minicipality.create(name:  "MELGAR")
# Minicipality.create(name:  "MERCADERES")
# Minicipality.create(name:  "MESETAS")
# Minicipality.create(name:  "MILAN")
# Minicipality.create(name:  "MIRAFLORES")
# Minicipality.create(name:  "MIRAFLORES")
# Minicipality.create(name:  "MIRANDA")
# Minicipality.create(name:  "MIRITI - PARANA")
# Minicipality.create(name:  "MISTRATO")
# Minicipality.create(name:  "MITU")
# Minicipality.create(name:  "MOCOA")
# Minicipality.create(name:  "MOGOTES")
# Minicipality.create(name:  "MOLAGAVITA")
# Minicipality.create(name:  "MOMIL")
# Minicipality.create(name:  "MOMPOS")
# Minicipality.create(name:  "MONGUA")
# Minicipality.create(name:  "MONGUI")
# Minicipality.create(name:  "MONIQUIRA")
# Minicipality.create(name:  "MONTEBELLO")
# Minicipality.create(name:  "MONTECRISTO")
# Minicipality.create(name:  "MONTELIBANO")
# Minicipality.create(name:  "MONTENEGRO")
# Minicipality.create(name:  "MONTERIA")
# Minicipality.create(name:  "MONTERREY")
# Minicipality.create(name:  "MOÑITOS")
# Minicipality.create(name:  "MORALES")
# Minicipality.create(name:  "MORALES")
# Minicipality.create(name:  "MORELIA")
# Minicipality.create(name:  "MORICHAL")
# Minicipality.create(name:  "MORROA")
# Minicipality.create(name:  "MOSQUERA")
# Minicipality.create(name:  "MOSQUERA")
# Minicipality.create(name:  "MOTAVITA")
# Minicipality.create(name:  "MURILLO")
# Minicipality.create(name:  "MURINDO")
# Minicipality.create(name:  "MUTATA")
# Minicipality.create(name:  "MUTISCUA")
# Minicipality.create(name:  "MUZO")
# Minicipality.create(name:  "NARIÑO")
# Minicipality.create(name:  "NARIÑO")
# Minicipality.create(name:  "NARIÑO")
# Minicipality.create(name:  "NATAGA")
# Minicipality.create(name:  "NATAGAIMA")
# Minicipality.create(name:  "NECHI")
# Minicipality.create(name:  "NECOCLI")
# Minicipality.create(name:  "NEIRA")
# Minicipality.create(name:  "NEIVA")
# Minicipality.create(name:  "NEMOCON")
# Minicipality.create(name:  "NILO")
# Minicipality.create(name:  "NIMAIMA")
# Minicipality.create(name:  "NOBSA")
# Minicipality.create(name:  "NOCAIMA")
# Minicipality.create(name:  "NORCASIA")
# Minicipality.create(name:  "NOROSI")
# Minicipality.create(name:  "NOVITA")
# Minicipality.create(name:  "NUEVA GRANADA")
# Minicipality.create(name:  "NUEVO COLON")
# Minicipality.create(name:  "NUNCHIA")
# Minicipality.create(name:  "NUQUI")
# Minicipality.create(name:  "OBANDO")
# Minicipality.create(name:  "OCAMONTE")
# Minicipality.create(name:  "OCAÑA")
# Minicipality.create(name:  "OIBA")
# Minicipality.create(name:  "OICATA")
# Minicipality.create(name:  "OLAYA")
# Minicipality.create(name:  "OLAYA HERRERA")
# Minicipality.create(name:  "ONZAGA")
# Minicipality.create(name:  "OPORAPA")
# Minicipality.create(name:  "ORITO")
# Minicipality.create(name:  "OROCUE")
# Minicipality.create(name:  "ORTEGA")
# Minicipality.create(name:  "OSPINA")
# Minicipality.create(name:  "OTANCHE")
# Minicipality.create(name:  "OVEJAS")
# Minicipality.create(name:  "PACHAVITA")
# Minicipality.create(name:  "PACHO")
# Minicipality.create(name:  "PACOA")
# Minicipality.create(name:  "PACORA")
# Minicipality.create(name:  "PADILLA")
# Minicipality.create(name:  "PAEZ")
# Minicipality.create(name:  "PAEZ")
# Minicipality.create(name:  "PAICOL")
# Minicipality.create(name:  "PAILITAS")
# Minicipality.create(name:  "PAIME")
# Minicipality.create(name:  "PAIPA")
# Minicipality.create(name:  "PAJARITO")
# Minicipality.create(name:  "PALERMO")
# Minicipality.create(name:  "PALESTINA")
# Minicipality.create(name:  "PALESTINA")
# Minicipality.create(name:  "PALMAR")
# Minicipality.create(name:  "PALMAR DE VARELA")
# Minicipality.create(name:  "PALMAS DEL SOCORRO")
# Minicipality.create(name:  "PALMIRA")
# Minicipality.create(name:  "PALMITO")
# Minicipality.create(name:  "PALOCABILDO")
# Minicipality.create(name:  "PAMPLONA")
# Minicipality.create(name:  "PAMPLONITA")
# Minicipality.create(name:  "PANA PANA")
# Minicipality.create(name:  "PANDI")
# Minicipality.create(name:  "PANQUEBA")
# Minicipality.create(name:  "PAPUNAUA")
# Minicipality.create(name:  "PARAMO")
# Minicipality.create(name:  "PARATEBUENO")
# Minicipality.create(name:  "PASCA")
# Minicipality.create(name:  "PASTO")
# Minicipality.create(name:  "PATIA")
# Minicipality.create(name:  "PAUNA")
# Minicipality.create(name:  "PAYA")
# Minicipality.create(name:  "PAZ DE ARIPORO")
# Minicipality.create(name:  "PAZ DE RIO")
# Minicipality.create(name:  "PEÐOL")
# Minicipality.create(name:  "PEDRAZA")
# Minicipality.create(name:  "PELAYA")
# Minicipality.create(name:  "PENSILVANIA")
# Minicipality.create(name:  "PEQUE")
# Minicipality.create(name:  "PEREIRA")
# Minicipality.create(name:  "PESCA")
# Minicipality.create(name:  "PIAMONTE")
# Minicipality.create(name:  "PIEDECUESTA")
# Minicipality.create(name:  "PIEDRAS")
# Minicipality.create(name:  "PIENDAMO")
# Minicipality.create(name:  "PIJAO")
# Minicipality.create(name:  "PIJIÑO DEL CARMEN")
# Minicipality.create(name:  "PINCHOTE")
# Minicipality.create(name:  "PINILLOS")
# Minicipality.create(name:  "PIOJO")
# Minicipality.create(name:  "PISBA")
# Minicipality.create(name:  "PITAL")
# Minicipality.create(name:  "PITALITO")
# Minicipality.create(name:  "PIVIJAY")
# Minicipality.create(name:  "PLANADAS")
# Minicipality.create(name:  "PLANETA RICA")
# Minicipality.create(name:  "PLATO")
# Minicipality.create(name:  "POLICARPA")
# Minicipality.create(name:  "POLONUEVO")
# Minicipality.create(name:  "PONEDERA")
# Minicipality.create(name:  "POPAYAN")
# Minicipality.create(name:  "PORE")
# Minicipality.create(name:  "POTOSI")
# Minicipality.create(name:  "PRADERA")
# Minicipality.create(name:  "PRADO")
# Minicipality.create(name:  "PROVIDENCIA")
# Minicipality.create(name:  "PROVIDENCIA")
# Minicipality.create(name:  "PUEBLO BELLO")
# Minicipality.create(name:  "PUEBLO NUEVO")
# Minicipality.create(name:  "PUEBLO RICO")
# Minicipality.create(name:  "PUEBLORRICO")
# Minicipality.create(name:  "PUEBLOVIEJO")
# Minicipality.create(name:  "PUENTE NACIONAL")
# Minicipality.create(name:  "PUERRES")
# Minicipality.create(name:  "PUERTO ALEGRIA")
# Minicipality.create(name:  "PUERTO ARICA")
# Minicipality.create(name:  "PUERTO ASIS")
# Minicipality.create(name:  "PUERTO BERRIO")
# Minicipality.create(name:  "PUERTO BOYACA")
# Minicipality.create(name:  "PUERTO CAICEDO")
# Minicipality.create(name:  "PUERTO CARREÑO")
# Minicipality.create(name:  "PUERTO COLOMBIA")
# Minicipality.create(name:  "PUERTO COLOMBIA")
# Minicipality.create(name:  "PUERTO CONCORDIA")
# Minicipality.create(name:  "PUERTO ESCONDIDO")
# Minicipality.create(name:  "PUERTO GAITAN")
# Minicipality.create(name:  "PUERTO GUZMAN")
# Minicipality.create(name:  "PUERTO LIBERTADOR")
# Minicipality.create(name:  "PUERTO LLERAS")
# Minicipality.create(name:  "PUERTO LOPEZ")
# Minicipality.create(name:  "PUERTO NARE")
# Minicipality.create(name:  "PUERTO NARIÑO")
# Minicipality.create(name:  "PUERTO PARRA")
# Minicipality.create(name:  "PUERTO RICO")
# Minicipality.create(name:  "PUERTO RICO")
# Minicipality.create(name:  "PUERTO RONDON")
# Minicipality.create(name:  "PUERTO SALGAR")
# Minicipality.create(name:  "PUERTO SANTANDER")
# Minicipality.create(name:  "PUERTO SANTANDER")
# Minicipality.create(name:  "PUERTO TEJADA")
# Minicipality.create(name:  "PUERTO TRIUNFO")
# Minicipality.create(name:  "PUERTO WILCHES")
# Minicipality.create(name:  "PULI")
# Minicipality.create(name:  "PUPIALES")
# Minicipality.create(name:  "PURACE")
# Minicipality.create(name:  "PURIFICACION")
# Minicipality.create(name:  "PURISIMA")
# Minicipality.create(name:  "QUEBRADANEGRA")
# Minicipality.create(name:  "QUETAME")
# Minicipality.create(name:  "QUIBDO")
# Minicipality.create(name:  "QUIMBAYA")
# Minicipality.create(name:  "QUINCHIA")
# Minicipality.create(name:  "QUIPAMA")
# Minicipality.create(name:  "QUIPILE")
# Minicipality.create(name:  "RAGONVALIA")
# Minicipality.create(name:  "RAMIRIQUI")
# Minicipality.create(name:  "RAQUIRA")
# Minicipality.create(name:  "RECETOR")
# Minicipality.create(name:  "REGIDOR")
# Minicipality.create(name:  "REMEDIOS")
# Minicipality.create(name:  "REMOLINO")
# Minicipality.create(name:  "REPELON")
# Minicipality.create(name:  "RESTREPO")
# Minicipality.create(name:  "RESTREPO")
# Minicipality.create(name:  "RETIRO")
# Minicipality.create(name:  "RICAURTE")
# Minicipality.create(name:  "RICAURTE")
# Minicipality.create(name:  "RIO DE ORO")
# Minicipality.create(name:  "RIO IRO")
# Minicipality.create(name:  "RIO QUITO")
# Minicipality.create(name:  "RIO VIEJO")
# Minicipality.create(name:  "RIOBLANCO")
# Minicipality.create(name:  "RIOFRIO")
# Minicipality.create(name:  "RIOHACHA")
# Minicipality.create(name:  "RIONEGRO")
# Minicipality.create(name:  "RIONEGRO")
# Minicipality.create(name:  "RIOSUCIO")
# Minicipality.create(name:  "RIOSUCIO")
# Minicipality.create(name:  "RISARALDA")
# Minicipality.create(name:  "RIVERA")
# Minicipality.create(name:  "ROBERTO PAYAN")
# Minicipality.create(name:  "ROLDANILLO")
# Minicipality.create(name:  "RONCESVALLES")
# Minicipality.create(name:  "RONDON")
# Minicipality.create(name:  "ROSAS")
# Minicipality.create(name:  "ROVIRA")
# Minicipality.create(name:  "SABANA DE TORRES")
# Minicipality.create(name:  "SABANAGRANDE")
# Minicipality.create(name:  "SABANALARGA")
# Minicipality.create(name:  "SABANALARGA")
# Minicipality.create(name:  "SABANALARGA")
# Minicipality.create(name:  "SABANAS DE SAN ANGEL")
# Minicipality.create(name:  "SABANETA")
# Minicipality.create(name:  "SABOYA")
# Minicipality.create(name:  "SACAMA")
# Minicipality.create(name:  "SACHICA")
# Minicipality.create(name:  "SAHAGUN")
# Minicipality.create(name:  "SALADOBLANCO")
# Minicipality.create(name:  "SALAMINA")
# Minicipality.create(name:  "SALAMINA")
# Minicipality.create(name:  "SALAZAR")
# Minicipality.create(name:  "SALDAÑA")
# Minicipality.create(name:  "SALENTO")
# Minicipality.create(name:  "SALGAR")
# Minicipality.create(name:  "SAMACA")
# Minicipality.create(name:  "SAMANA")
# Minicipality.create(name:  "SAMANIEGO")
# Minicipality.create(name:  "SAMPUES")
# Minicipality.create(name:  "SAN AGUSTIN")
# Minicipality.create(name:  "SAN ALBERTO")
# Minicipality.create(name:  "SAN ANDRES")
# Minicipality.create(name:  "SAN ANDRES")
# Minicipality.create(name:  "SAN ANDRES DE CUERQUIA")
# Minicipality.create(name:  "SAN ANDRES DE TUMACO")
# Minicipality.create(name:  "SAN ANDRES SOTAVENTO")
# Minicipality.create(name:  "SAN ANTERO")
# Minicipality.create(name:  "SAN ANTONIO")
# Minicipality.create(name:  "SAN ANTONIO DEL TEQUENDAMA")
# Minicipality.create(name:  "SAN BENITO")
# Minicipality.create(name:  "SAN BENITO ABAD")
# Minicipality.create(name:  "SAN BERNARDO")
# Minicipality.create(name:  "SAN BERNARDO")
# Minicipality.create(name:  "SAN BERNARDO DEL VIENTO")
# Minicipality.create(name:  "SAN CALIXTO")
# Minicipality.create(name:  "SAN CARLOS")
# Minicipality.create(name:  "SAN CARLOS")
# Minicipality.create(name:  "SAN CARLOS DE GUAROA")
# Minicipality.create(name:  "SAN CAYETANO")
# Minicipality.create(name:  "SAN CAYETANO")
# Minicipality.create(name:  "SAN CRISTOBAL")
# Minicipality.create(name:  "SAN DIEGO")
# Minicipality.create(name:  "SAN EDUARDO")
# Minicipality.create(name:  "SAN ESTANISLAO")
# Minicipality.create(name:  "SAN FELIPE")
# Minicipality.create(name:  "SAN FERNANDO")
# Minicipality.create(name:  "SAN FRANCISCO")
# Minicipality.create(name:  "SAN FRANCISCO")
# Minicipality.create(name:  "SAN FRANCISCO")
# Minicipality.create(name:  "SAN GIL")
# Minicipality.create(name:  "SAN JACINTO")
# Minicipality.create(name:  "SAN JACINTO DEL CAUCA")
# Minicipality.create(name:  "SAN JERONIMO")
# Minicipality.create(name:  "SAN JOAQUIN")
# Minicipality.create(name:  "SAN JOSE")
# Minicipality.create(name:  "SAN JOSE DE LA MONTAÑA")
# Minicipality.create(name:  "SAN JOSE DE MIRANDA")
# Minicipality.create(name:  "SAN JOSE DE PARE")
# Minicipality.create(name:  "SAN JOSE DEL FRAGUA")
# Minicipality.create(name:  "SAN JOSE DEL GUAVIARE")
# Minicipality.create(name:  "SAN JOSE DEL PALMAR")
# Minicipality.create(name:  "SAN JUAN DE ARAMA")
# Minicipality.create(name:  "SAN JUAN DE BETULIA")
# Minicipality.create(name:  "SAN JUAN DE RIO SECO")
# Minicipality.create(name:  "SAN JUAN DE URABA")
# Minicipality.create(name:  "SAN JUAN DEL CESAR")
# Minicipality.create(name:  "SAN JUAN NEPOMUCENO")
# Minicipality.create(name:  "SAN JUANITO")
# Minicipality.create(name:  "SAN LORENZO")
# Minicipality.create(name:  "SAN LUIS")
# Minicipality.create(name:  "SAN LUIS")
# Minicipality.create(name:  "SAN LUIS DE GACENO")
# Minicipality.create(name:  "SAN LUIS DE PALENQUE")
# Minicipality.create(name:  "SAN LUIS DE SINCE")
# Minicipality.create(name:  "SAN MARCOS")
# Minicipality.create(name:  "SAN MARTIN")
# Minicipality.create(name:  "SAN MARTIN")
# Minicipality.create(name:  "SAN MARTIN DE LOBA")
# Minicipality.create(name:  "SAN MATEO")
# Minicipality.create(name:  "SAN MIGUEL")
# Minicipality.create(name:  "SAN MIGUEL")
# Minicipality.create(name:  "SAN MIGUEL DE SEMA")
# Minicipality.create(name:  "SAN ONOFRE")
# Minicipality.create(name:  "SAN PABLO")
# Minicipality.create(name:  "SAN PABLO")
# Minicipality.create(name:  "SAN PABLO DE BORBUR")
# Minicipality.create(name:  "SAN PEDRO")
# Minicipality.create(name:  "SAN PEDRO")
# Minicipality.create(name:  "SAN PEDRO")
# Minicipality.create(name:  "SAN PEDRO DE CARTAGO")
# Minicipality.create(name:  "SAN PEDRO DE URABA")
# Minicipality.create(name:  "SAN PELAYO")
# Minicipality.create(name:  "SAN RAFAEL")
# Minicipality.create(name:  "SAN ROQUE")
# Minicipality.create(name:  "SAN SEBASTIAN")
# Minicipality.create(name:  "SAN SEBASTIAN DE BUENAVISTA")
# Minicipality.create(name:  "SAN VICENTE")
# Minicipality.create(name:  "SAN VICENTE DE CHUCURI")
# Minicipality.create(name:  "SAN VICENTE DEL CAGUAN")
# Minicipality.create(name:  "SAN ZENON")
# Minicipality.create(name:  "SANDONA")
# Minicipality.create(name:  "SANTA ANA")
# Minicipality.create(name:  "SANTA BARBARA")
# Minicipality.create(name:  "SANTA BARBARA")
# Minicipality.create(name:  "SANTA BARBARA")
# Minicipality.create(name:  "SANTA BARBARA DE PINTO")
# Minicipality.create(name:  "SANTA CATALINA")
# Minicipality.create(name:  "SANTA HELENA DEL OPON")
# Minicipality.create(name:  "SANTA ISABEL")
# Minicipality.create(name:  "SANTA LUCIA")
# Minicipality.create(name:  "SANTA MARIA")
# Minicipality.create(name:  "SANTA MARIA")
# Minicipality.create(name:  "SANTA MARTA")
# Minicipality.create(name:  "SANTA ROSA")
# Minicipality.create(name:  "SANTA ROSA")
# Minicipality.create(name:  "SANTA ROSA DE CABAL")
# Minicipality.create(name:  "SANTA ROSA DE OSOS")
# Minicipality.create(name:  "SANTA ROSA DE VITERBO")
# Minicipality.create(name:  "SANTA ROSA DEL SUR")
# Minicipality.create(name:  "SANTA ROSALIA")
# Minicipality.create(name:  "SANTA SOFIA")
# Minicipality.create(name:  "SANTACRUZ")
# Minicipality.create(name:  "SANTAFE DE ANTIOQUIA")
# Minicipality.create(name:  "SANTANA")
# Minicipality.create(name:  "SANTANDER DE QUILICHAO")
# Minicipality.create(name:  "SANTIAGO")
# Minicipality.create(name:  "SANTIAGO")
# Minicipality.create(name:  "SANTIAGO DE TOLU")
# Minicipality.create(name:  "SANTO DOMINGO")
# Minicipality.create(name:  "SANTO TOMAS")
# Minicipality.create(name:  "SANTUARIO")
# Minicipality.create(name:  "SAPUYES")
# Minicipality.create(name:  "SARAVENA")
# Minicipality.create(name:  "SARDINATA")
# Minicipality.create(name:  "SASAIMA")
# Minicipality.create(name:  "SATIVANORTE")
# Minicipality.create(name:  "SATIVASUR")
# Minicipality.create(name:  "SEGOVIA")
# Minicipality.create(name:  "SESQUILE")
# Minicipality.create(name:  "SEVILLA")
# Minicipality.create(name:  "SIACHOQUE")
# Minicipality.create(name:  "SIBATE")
# Minicipality.create(name:  "SIBUNDOY")
# Minicipality.create(name:  "SILOS")
# Minicipality.create(name:  "SILVANIA")
# Minicipality.create(name:  "SILVIA")
# Minicipality.create(name:  "SIMACOTA")
# Minicipality.create(name:  "SIMIJACA")
# Minicipality.create(name:  "SIMITI")
# Minicipality.create(name:  "SINCELEJO")
# Minicipality.create(name:  "SIPI")
# Minicipality.create(name:  "SITIONUEVO")
# Minicipality.create(name:  "SOACHA")
# Minicipality.create(name:  "SOATA")
# Minicipality.create(name:  "SOCHA")
# Minicipality.create(name:  "SOCORRO")
# Minicipality.create(name:  "SOCOTA")
# Minicipality.create(name:  "SOGAMOSO")
# Minicipality.create(name:  "SOLANO")
# Minicipality.create(name:  "SOLEDAD")
# Minicipality.create(name:  "SOLITA")
# Minicipality.create(name:  "SOMONDOCO")
# Minicipality.create(name:  "SONSON")
# Minicipality.create(name:  "SOPETRAN")
# Minicipality.create(name:  "SOPLAVIENTO")
# Minicipality.create(name:  "SOPO")
# Minicipality.create(name:  "SORA")
# Minicipality.create(name:  "SORACA")
# Minicipality.create(name:  "SOTAQUIRA")
# Minicipality.create(name:  "SOTARA")
# Minicipality.create(name:  "SUAITA")
# Minicipality.create(name:  "SUAN")
# Minicipality.create(name:  "SUAREZ")
# Minicipality.create(name:  "SUAREZ")
# Minicipality.create(name:  "SUAZA")
# Minicipality.create(name:  "SUBACHOQUE")
# Minicipality.create(name:  "SUCRE")
# Minicipality.create(name:  "SUCRE")
# Minicipality.create(name:  "SUCRE")
# Minicipality.create(name:  "SUESCA")
# Minicipality.create(name:  "SUPATA")
# Minicipality.create(name:  "SUPIA")
# Minicipality.create(name:  "SURATA")
# Minicipality.create(name:  "SUSA")
# Minicipality.create(name:  "SUSACON")
# Minicipality.create(name:  "SUTAMARCHAN")
# Minicipality.create(name:  "SUTATAUSA")
# Minicipality.create(name:  "SUTATENZA")
# Minicipality.create(name:  "TABIO")
# Minicipality.create(name:  "TADO")
# Minicipality.create(name:  "TALAIGUA NUEVO")
# Minicipality.create(name:  "TAMALAMEQUE")
# Minicipality.create(name:  "TAMARA")
# Minicipality.create(name:  "TAME")
# Minicipality.create(name:  "TAMESIS")
# Minicipality.create(name:  "TAMINANGO")
# Minicipality.create(name:  "TANGUA")
# Minicipality.create(name:  "TARAIRA")
# Minicipality.create(name:  "TARAPACA")
# Minicipality.create(name:  "TARAZA")
# Minicipality.create(name:  "TARQUI")
# Minicipality.create(name:  "TARSO")
# Minicipality.create(name:  "TASCO")
# Minicipality.create(name:  "TAURAMENA")
# Minicipality.create(name:  "TAUSA")
# Minicipality.create(name:  "TELLO")
# Minicipality.create(name:  "TENA")
# Minicipality.create(name:  "TENERIFE")
# Minicipality.create(name:  "TENJO")
# Minicipality.create(name:  "TENZA")
# Minicipality.create(name:  "TEORAMA")
# Minicipality.create(name:  "TERUEL")
# Minicipality.create(name:  "TESALIA")
# Minicipality.create(name:  "TIBACUY")
# Minicipality.create(name:  "TIBANA")
# Minicipality.create(name:  "TIBASOSA")
# Minicipality.create(name:  "TIBIRITA")
# Minicipality.create(name:  "TIBU")
# Minicipality.create(name:  "TIERRALTA")
# Minicipality.create(name:  "TIMANA")
# Minicipality.create(name:  "TIMBIO")
# Minicipality.create(name:  "TIMBIQUI")
# Minicipality.create(name:  "TINJACA")
# Minicipality.create(name:  "TIPACOQUE")
# Minicipality.create(name:  "TIQUISIO")
# Minicipality.create(name:  "TITIRIBI")
# Minicipality.create(name:  "TOCA")
# Minicipality.create(name:  "TOCAIMA")
# Minicipality.create(name:  "TOCANCIPA")
# Minicipality.create(name:  "TOGsI")
# Minicipality.create(name:  "TOLEDO")
# Minicipality.create(name:  "TOLEDO")
# Minicipality.create(name:  "TOLU VIEJO")
# Minicipality.create(name:  "TONA")
# Minicipality.create(name:  "TOPAGA")
# Minicipality.create(name:  "TOPAIPI")
# Minicipality.create(name:  "TORIBIO")
# Minicipality.create(name:  "TORO")
# Minicipality.create(name:  "TOTA")
# Minicipality.create(name:  "TOTORO")
# Minicipality.create(name:  "TRINIDAD")
# Minicipality.create(name:  "TRUJILLO")
# Minicipality.create(name:  "TUBARA")
# Minicipality.create(name:  "TULUA")
# Minicipality.create(name:  "TUNJA")
# Minicipality.create(name:  "TUNUNGUA")
# Minicipality.create(name:  "TUQUERRES")
# Minicipality.create(name:  "TURBACO")
# Minicipality.create(name:  "TURBANA")
# Minicipality.create(name:  "TURBO")
# Minicipality.create(name:  "TURMEQUE")
# Minicipality.create(name:  "TUTA")
# Minicipality.create(name:  "TUTAZA")
# Minicipality.create(name:  "UBALA")
# Minicipality.create(name:  "UBAQUE")
# Minicipality.create(name:  "ULLOA")
# Minicipality.create(name:  "UMBITA")
# Minicipality.create(name:  "UNE")
# Minicipality.create(name:  "UNGUIA")
# Minicipality.create(name:  "UNION PANAMERICANA")
# Minicipality.create(name:  "URAMITA")
# Minicipality.create(name:  "URIBE")
# Minicipality.create(name:  "URIBIA")
# Minicipality.create(name:  "URRAO")
# Minicipality.create(name:  "URUMITA")
# Minicipality.create(name:  "USIACURI")
# Minicipality.create(name:  "UTICA")
# Minicipality.create(name:  "VALDIVIA")
# Minicipality.create(name:  "VALENCIA")
# Minicipality.create(name:  "VALLE DE SAN JOSE")
# Minicipality.create(name:  "VALLE DE SAN JUAN")
# Minicipality.create(name:  "VALLE DEL GUAMUEZ")
# Minicipality.create(name:  "VALLEDUPAR")
# Minicipality.create(name:  "VALPARAISO")
# Minicipality.create(name:  "VALPARAISO")
# Minicipality.create(name:  "VEGACHI")
# Minicipality.create(name:  "VELEZ")
# Minicipality.create(name:  "VENADILLO")
# Minicipality.create(name:  "VENECIA")
# Minicipality.create(name:  "VENECIA")
# Minicipality.create(name:  "VENTAQUEMADA")
# Minicipality.create(name:  "VERGARA")
# Minicipality.create(name:  "VERSALLES")
# Minicipality.create(name:  "VETAS")
# Minicipality.create(name:  "VIANI")
# Minicipality.create(name:  "VICTORIA")
# Minicipality.create(name:  "VIGIA DEL FUERTE")
# Minicipality.create(name:  "VIJES")
# Minicipality.create(name:  "VILLA CARO")
# Minicipality.create(name:  "VILLA DE LEYVA")
# Minicipality.create(name:  "VILLA DE SAN DIEGO DE UBATE")
# Minicipality.create(name:  "VILLA DEL ROSARIO")
# Minicipality.create(name:  "VILLA RICA")
# Minicipality.create(name:  "VILLAGARZON")
# Minicipality.create(name:  "VILLAGOMEZ")
# Minicipality.create(name:  "VILLAHERMOSA")
# Minicipality.create(name:  "VILLAMARIA")
# Minicipality.create(name:  "VILLANUEVA")
# Minicipality.create(name:  "VILLANUEVA")
# Minicipality.create(name:  "VILLANUEVA")
# Minicipality.create(name:  "VILLANUEVA")
# Minicipality.create(name:  "VILLAPINZON")
# Minicipality.create(name:  "VILLARRICA")
# Minicipality.create(name:  "VILLAVICENCIO")
# Minicipality.create(name:  "VILLAVIEJA")
# Minicipality.create(name:  "VILLETA")
# Minicipality.create(name:  "VIOTA")
# Minicipality.create(name:  "VIRACACHA")
# Minicipality.create(name:  "VISTAHERMOSA")
# Minicipality.create(name:  "VITERBO")
# Minicipality.create(name:  "YACOPI")
# Minicipality.create(name:  "YACUANQUER")
# Minicipality.create(name:  "YAGUARA")
# Minicipality.create(name:  "YALI")
# Minicipality.create(name:  "YARUMAL")
# Minicipality.create(name:  "YAVARATE")
# Minicipality.create(name:  "YOLOMBO")
# Minicipality.create(name:  "YONDO")
# Minicipality.create(name:  "YOPAL")
# Minicipality.create(name:  "YOTOCO")
# Minicipality.create(name:  "YUMBO")
# Minicipality.create(name:  "ZAMBRANO")
# Minicipality.create(name:  "ZAPATOCA")
# Minicipality.create(name:  "ZAPAYAN")
# Minicipality.create(name:  "ZARAGOZA")
# Minicipality.create(name:  "ZARZAL")
# Minicipality.create(name:  "ZETAQUIRA")
# Minicipality.create(name:  "ZIPACON")
# Minicipality.create(name:  "ZIPAQUIRA")
# Minicipality.create(name:  "ZONA BANANERA")

####Usuarios 20

    v = Voluntary.new(
        gender: Faker::Lovecraft.deity,
        cellphone: "320320420",
        voluntary_score: 5,
	city: "Hazing"
        )
    v.save!

    u = User.new(
        email: "adavilam@unal.edu.co",#Faker::Internet.free_email,
        password: "123456789",
        name: Faker::HarryPotter.character,
        username: Faker::Internet.user_name,
        password_confirmation: "123456789"
        )
    u.save!

    up = UserPolymorphism.create(
	user_id: u.id,
        user_data_id: v.id,
        user_data_type: "Voluntary")
    #up.save!


20.times do
    o = Organization.new(
        NIT: Faker::Color.hex_color,
        mainaddress: Faker::Zelda.game,
        firm: Faker::Hacker.say_something_smart,
        organization_score: 5
        )
    o.save!

    u = User.new(
        email: Faker::Internet.free_email,
        password: "123456789",
        name: Faker::HarryPotter.character,
        username: Faker::Internet.user_name,
        password_confirmation: "123456789"
        )
    u.save!

    up = UserPolymorphism.new(
	user_id: u.id,
        user_data_id: o.id,
        user_data_type: "Organization")
    up.save!
end


Event.create(organization_id: 2,
	name: "Testing",
	description: Faker::Lovecraft.fhtagn(10),
	duration: 5,
	)

EventVoluntary.create(voluntary_id: 1,
	event_id: 1)

Admin.create(email: "caralopezrom@unal.edu.co",
                password: "123456789",
                password_confirmation: "123456789",
                username: "caralopezrom",
                name: "Carlos Arturo lopez Romero")
Admin.create(email: "adavilame@unal.edu.co ",
    password: "123456789",
    password_confirmation: "123456789",
    username: "adavilam",
    name: "Angel David Avila ")

TypeContact.create(name: "Queja")
TypeContact.create(name: "Peticion")
TypeContact.create(name: "Reclamo")
